### ISSUE TITLE
ImportError: cannot import name 'ScepenabledError' from 'rdmc_helper'

### ISSUE THREAD

**Issue by rafiqkattangere** [HewlettPackard/python-redfish-utility#58]
Can you fix this pls.

PS C:\Users\KAhamedR\Downloads\python-redfish-utility-master\src> py.exe .\rdmc.py
Traceback (most recent call last):
  File "C:\Users\KAhamedR\Downloads\python-redfish-utility-master\src\rdmc.py", line 49, in <module>
    import redfish.ris
  File "C:\Python39\lib\site-packages\redfish\ris\__init__.py", line 34, in <module>
    from .rmc import (
  File "C:\Python39\lib\site-packages\redfish\ris\rmc.py", line 39, in <module>
    from redfish.ris.resp_handler import ResponseHandler
    from rdmc_helper import IloLicenseError , ScepenabledError
ImportError: cannot import name 'ScepenabledError' from 'rdmc_helper' (C:\Users\KAhamedR\Downloads\python-redfish-utility-master\src\rdmc_helper.py)
PS C:\Users\KAhamedR\Downloads\python-redfish-utility-master\src> python.exe .\rdmc.py
Traceback (most recent call last):
  File "C:\Users\KAhamedR\Downloads\python-redfish-utility-master\src\rdmc.py", line 49, in <module>
    import redfish.ris
  File "C:\Python39\lib\site-packages\redfish\ris\__init__.py", line 34, in <module>

**Comment by rajeevkallur** [comment]
@rafiqkattangere , Please  check now. I have added that exception.
