### ISSUE TITLE
Unable to connect to servers using ilorest

### ISSUE THREAD

**Issue by vishybhai** [HewlettPackard/python-redfish-utility#85]
I get below error when trying to use ilo rest. 
ilorest get --select Bios. --url 90.25.136.187 -u root -p eoif....
iLORest : RESTful Interface Tool version 4.5.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
^CTraceback (most recent call last):
  File "rdmc.py", line 1211, in <module>
  File "rdmc.py", line 1198, in ilorestcommand
  File "rdmc.py", line 534, in run
  File "rdmc.py", line 378, in _run_command
  File "extensions/COMMANDS/GetCommand.py", line 92, in run
  File "extensions/COMMANDS/GetCommand.py", line 287, in getvalidation
  File "rdmc_base_classes.py", line 201, in login_select_validation
  File "extensions/COMMANDS/LoginCommand.py", line 212, in loginfunction
  File "redfish/ris/rmc.py", line 255, in login
  File "redfish/ris/gen_compat.py", line 112, in getgen
  File "redfish/rest/v1.py", line 616, in __init__
  File "redfish/rest/v1.py", line 272, in __init__
  File "redfish/rest/v1.py", line 85, in __init__
  File "redfish/rest/v1.py", line 116, in _build_connection
  File "redfish/rest/connections.py", line 136, in __init__
  File "redfish/rest/connections.py", line 157, in _init_connection
  File "urllib3/util/retry.py", line 277, in __init__
KeyboardInterrupt
[55640] Failed to execute script 'rdmc' due to unhandled exception!

Command gets hanged and so I interrupt. CentOS-7.9 
python --version
Python 2.7.5

**Comment by rajeevkallur** [comment]
@vishybhai ,  Please check if 90.25.136.187  is reachable or pinging.  If it is not reachable, please wait until error is printed.

**Comment by rajeevkallur** [comment]
Please use ilorest -v -d to collect additional ilorest log

**Comment by rajeevkallur** [comment]
No response. Closing.
