### ISSUE TITLE
enable_nic not working

### ISSUE THREAD

**Issue by woertz** [HewlettPackard/python-redfish-utility#99]
Even after iLO update it is not working.
```
# ilorest ethernet --enable_nic 1 -d
iLORest : RESTful Interface Tool version 5.1.0.0
Copyright (c) 2014-2024 Hewlett Packard Enterprise Development LP
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INFO    : Exception: TypeError(int() argument must be a string, a bytes-like object or a real number, not 'NoneType')
ERROR: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback (most recent call last):
  File "rdmc.py", line 528, in run
  File "rdmc.py", line 372, in _run_command
  File "extensions/iLO_COMMANDS/EthernetCommand.py", line 235, in run
  File "extensions/iLO_COMMANDS/EthernetCommand.py", line 387, in enable_disable_nics
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
DEBUG   : Calling ChifClose...
```
NIC is not enabled:
```
# ilorest --nologo rawget '/redfish/v1/Managers/1/EthernetInterfaces/1/?$select=Oem/Hpe/InterfaceType,Oem/Hpe/NICEnabled'
{
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.etag": "W/\"68F6A37D\"",
  "@odata.id": "/redfish/v1/Managers/1/EthernetInterfaces/1/",
  "@odata.type": "#EthernetInterface.v1_4_1.EthernetInterface",
  "Oem": {
    "Hpe": {
      "InterfaceType": "Dedicated",
      "NICEnabled": false
    }
  }
}

```

There are no changes:
```
# ilorest --nologo status
No changes found
```

Latest iLO version:
```
# ilorest --nologo get --select Manager. FirmwareVersion
FirmwareVersion=iLO 6 v1.61
```

**Comment by rajeevkallur** [comment]
Not able to reproduce. Please feel to reopen if it is really an issue
